-- CÂU LỆNH SQL ĐỂ TẠO BẢNG NHẬT KÝ THAY ĐỔI (AUDIT LOGS)
-- Dùng để theo dõi ai đã sửa dữ liệu, sửa lúc nào và giá trị cũ là bao nhiêu

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL, -- Có thể là ID số hoặc chuỗi
    action TEXT NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    old_data JSONB,
    new_data JSONB,
    changed_by TEXT, -- Lưu mã nhân viên (MNV)
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cho phép đọc/ghi tự do (Tùy chỉnh RLS sau nếu cần để bảo mật hơn)
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

-- Index để tìm kiếm nhanh theo bảng hoặc bản ghi
CREATE INDEX IF NOT EXISTS idx_audit_table ON audit_logs(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_record ON audit_logs(record_id);
