-- CÂU LỆNH SQL ĐỂ TẠO BẢNG LỘ TRÌNH (LOTRINH)
-- Dùng để lưu trữ dữ liệu từ tab Lộ Trình Vận Chuyển

CREATE TABLE IF NOT EXISTS lotrinh (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_lotrinh TEXT DEFAULT 'Lộ Trình Vận Chuyển',
    ma_nv TEXT, -- Người lập (MNV)
    stops JSONB, -- Lưu mảng danh sách các điểm: {ten, tg_dung, km_tiep, tg_chay}
    tong_km NUMERIC,
    tong_phut NUMERIC,
    ngay_lap DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cho phép đọc/ghi tự do (Tùy chỉnh RLS sau nếu cần)
ALTER TABLE lotrinh DISABLE ROW LEVEL SECURITY;
