const axios = require('axios');

const SUPABASE_URL = "https://mpuqcmektepsqsazuvtb.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdXFjbWVrdGVwc3FzYXp1dnRiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzE0NjU5OCwiZXhwIjoyMDg4NzIyNTk4fQ.eBWCfXV5v4SNSICYg_wVwaez9ycRk7-XmTry7UnHTU8";

const tables = {
  xe: `
    CREATE TABLE IF NOT EXISTS xe (
        bien_so_xe TEXT PRIMARY KEY,
        loai_xe TEXT,
        tai_trong TEXT,
        nam_sx TEXT,
        so_khung TEXT,
        so_may TEXT,
        ma_loai TEXT,
        thung_dai TEXT,
        thung_rong TEXT,
        thung_cao TEXT,
        kich_thuoc_thung TEXT,
        the_tich_thung TEXT,
        khoi_luong_ban_than TEXT,
        khoi_luong_cho_phep TEXT,
        so_dang_ky TEXT,
        ngay_dang_ky TEXT,
        cb_dk NUMERIC,
        so_dang_kiem TEXT,
        ngay_dang_kiem TEXT,
        cb_dkiem NUMERIC,
        so_phu_hieu TEXT,
        ngay_phu_hieu TEXT,
        cb_ph NUMERIC,
        so_bao_hiem TEXT,
        ngay_bao_hiem TEXT,
        cb_bh NUMERIC,
        tinh_trang_hoat_dong TEXT DEFAULT 'dang_hoat_dong',
        loai_bien_so TEXT,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  taixe: `
    CREATE TABLE IF NOT EXISTS taixe (
        ma_nv TEXT PRIMARY KEY,
        ho_ten TEXT,
        nam_sinh TEXT,
        gioi_tinh TEXT,
        cccd TEXT,
        sdt TEXT,
        que_quan TEXT,
        hang_gplx TEXT,
        so_gplx TEXT,
        ngay_trung_tuyen TEXT,
        noi_cap TEXT,
        han_gplx TEXT,
        ngay_nhan_viec TEXT,
        thu_viec TEXT,
        chinh_thuc TEXT,
        ghi_chu TEXT,
        xe_phu_trach TEXT,
        tuyen_phu_trach TEXT,
        bl_ho_ten TEXT,
        bl_quan_he TEXT,
        bl_sdt TEXT,
        bl_que_quan TEXT,
        hs_cccd BOOLEAN DEFAULT FALSE,
        hs_gplx BOOLEAN DEFAULT FALSE,
        hs_suc_khoe BOOLEAN DEFAULT FALSE,
        hs_so_yeu BOOLEAN DEFAULT FALSE,
        hs_cu_tru BOOLEAN DEFAULT FALSE,
        hs_dan_su BOOLEAN DEFAULT FALSE,
        role TEXT DEFAULT 'driver',
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  nhatky: `
    CREATE TABLE IF NOT EXISTS nhatky (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bien_so_xe TEXT,
        mnv TEXT,
        tai_xe TEXT,
        ngay_van_hanh TEXT,
        chuyen_so TEXT,
        loai_chuyen TEXT,
        gio_xuat TEXT,
        gio_ve TEXT,
        tong_gio NUMERIC,
        km_xuat NUMERIC,
        km_ve NUMERIC,
        tong_km NUMERIC,
        suco_toggle TEXT,
        van_de_phat_sinh TEXT,
        tu_danh_gia TEXT,
        de_xuat_pa TEXT,
        ghi_chu TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  fuel: `
    CREATE TABLE IF NOT EXISTS fuel (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bien_so_xe TEXT,
        km_sau NUMERIC,
        ngay_thuc_hien TEXT,
        gio_thuc_hien TEXT,
        loai TEXT,
        so_lit NUMERIC,
        don_gia NUMERIC,
        thanh_tien NUMERIC,
        don_vi TEXT,
        hoa_don TEXT,
        ghi_chu TEXT,
        km_truoc NUMERIC,
        km_chenh_lech NUMERIC,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  baoduong: `
    CREATE TABLE IF NOT EXISTS baoduong (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bien_so_xe TEXT,
        loai_hinh TEXT,
        km_sau NUMERIC,
        moc_bao_duong TEXT,
        ngay_bat_dau TEXT,
        ngay_ket_thuc TEXT,
        tong_ngay NUMERIC,
        don_vi TEXT,
        loai_don_vi TEXT,
        hang_muc TEXT,
        phat_sinh TEXT,
        ket_qua TEXT,
        loai_thanh_toan TEXT,
        hoa_don TEXT,
        tong_tien NUMERIC,
        ghi_chu TEXT,
        km_truoc NUMERIC,
        km_chenh_lech NUMERIC,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  nhiemvu: `
    CREATE TABLE IF NOT EXISTS nhiemvu (
        id TEXT PRIMARY KEY,
        nguoi_giao TEXT,
        nguoi_nhan TEXT,
        loai_nhiem_vu TEXT,
        trang_thai TEXT,
        noi_dung TEXT,
        ngay_bat_dau TEXT,
        han_hoan_thanh TEXT,
        ket_qua TEXT,
        ghi_chu TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  diemgiaohang: `
    CREATE TABLE IF NOT EXISTS diemgiaohang (
        id TEXT PRIMARY KEY,
        ten_diem TEXT,
        dia_chi TEXT,
        maps_link TEXT,
        lat TEXT,
        lng TEXT,
        ghi_chu TEXT,
        created_by TEXT,
        updated_by TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  danhgia: `
    CREATE TABLE IF NOT EXISTS danhgia (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ma_nv TEXT,
        ho_ten TEXT,
        ngay TEXT,
        loi TEXT,
        muc_do TEXT,
        so_lan NUMERIC,
        ket_luan TEXT,
        ghi_chu TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `,
  dangkylich: `
    CREATE TABLE IF NOT EXISTS dangkylich (
        id TEXT PRIMARY KEY,
        ma_nv TEXT,
        ho_ten TEXT,
        thang_nam TEXT,
        cac_ngay TEXT,
        loai_nghi TEXT,
        ly_do TEXT,
        trang_thai TEXT DEFAULT 'Chờ duyệt',
        nguoi_duyet TEXT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
  `
};

async function setupDatabase() {
  console.log('--- Đang bắt đầu khởi tạo cấu trúc Database trên Supabase ---');
  
  for (const [name, sql] of Object.entries(tables)) {
    try {
      console.log(`Đang tạo bảng: ${name}...`);
      await axios.post(`${SUPABASE_URL}/rest/v1/rpc/run_sql_manual`, {
        sql_query: sql
      }, {
        headers: {
          'apikey': SUPABASE_KEY,
          'Authorization': `Bearer ${SUPABASE_KEY}`,
          'Content-Type': 'application/json'
        }
      });
      console.log(`✅ Hoàn thành bảng: ${name}`);
    } catch (err) {
      // Vì Supabase REST API KHÔNG hỗ trợ chạy SQL trực tiếp trừ khi có hàm RPC
      // Tôi sẽ thử dùng cách khác nếu rpc không tồn tại
      console.log(`❌ Bảng ${name} có thể cần khởi tạo qua SQL Editor trực tiếp hoặc cấu hình thêm.`);
      console.log('Lỗi:', err.response ? err.response.data : err.message);
    }
  }
  
  console.log('--- Kết thúc tiến trình ---');
}

// Lưu ý: RPC run_sql_manual thường không có sẵn mặc định, đoạn code này nhằm mục đích minh họa
// Tôi sẽ cung cấp lệnh SQL để bạn dán vào SQL Editor vì đó là cách an toàn và chuẩn nhất.
setupDatabase();
