-- QUẢN LÝ ĐỘI XE - SQL SETUP SCRIPT
-- Copy và chạy script này trong Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. TẠO BẢNG CHI PHÍ VẬN HÀNH (Chưa tồn tại)
CREATE TABLE IF NOT EXISTS public.chiphi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    ngay_thuc_hien DATE NOT NULL,
    loai_chi_phi TEXT,
    bien_so_xe TEXT,
    so_tien NUMERIC DEFAULT 0,
    ma_nv TEXT,
    ho_ten_taixe TEXT,
    ghi_chu TEXT,
    ma_hoa_don TEXT
);

-- 2. TẠO BẢNG NHẬT KÝ HỆ THỐNG (Audit Logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at TIMESTAMPTZ DEFAULT NOW(),
    table_name TEXT,
    record_id TEXT,
    action TEXT,
    changed_by TEXT,
    old_data JSONB,
    new_data JSONB
);

-- 3. CẤU HÌNH QUYỀN TRUY CẬP (RLS) - Dành cho môi trường Dev/Test
-- (Lưu ý: Bạn nên cấu hình bảo mật hơn cho môi trường Production)
ALTER TABLE public.chiphi ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for chiphi" ON public.chiphi;
CREATE POLICY "Enable all access for chiphi" ON public.chiphi FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for audit_logs" ON public.audit_logs;
CREATE POLICY "Enable all access for audit_logs" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);

-- 4. TẠO INDEX ĐỂ TĂNG TỐC TRUY VẤN BÁO CÁO
CREATE INDEX IF NOT EXISTS idx_chiphi_ngay ON public.chiphi (ngay_thuc_hien);
CREATE INDEX IF NOT EXISTS idx_chiphi_xe ON public.chiphi (bien_so_xe);
